In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("iris.csv")

In [3]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

Describing dataset

In [4]:
print(df.shape,end="\n\n\n")
print(df.describe(),end="\n\n\n")
print(df.columns,end="\n\n\n")
print(df.head(3),end="\n\n\n")
#df.columns=[i for i in range(5)]
df

(150, 5)


       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa




sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
df.iloc[6:11,4]

6     setosa
7     setosa
8     setosa
9     setosa
10    setosa
Name: species, dtype: object

Filtering and preprocessing data

In [6]:
df.species.value_counts()
x=df.iloc[:,:4]
y=df.iloc[:,4]
print(x,y)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns] 0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


splitting data into training data and testing data

In [7]:
from sklearn.model_selection import train_test_split as tts
x_train,x_test,y_train,y_test=tts(x,y,test_size=0.25,random_state=1)
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(112, 4) (38, 4) (112,) (38,)


Fitting data to the model

In [8]:
from sklearn.neighbors import KNeighborsClassifier as kn
knn=kn(n_neighbors=1)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)
for x,y in zip(y_pred,y_test):
  print(x+"    "+y)

setosa    setosa
versicolor    versicolor
versicolor    versicolor
setosa    setosa
virginica    virginica
versicolor    versicolor
virginica    virginica
setosa    setosa
setosa    setosa
virginica    virginica
versicolor    versicolor
setosa    setosa
virginica    virginica
versicolor    versicolor
versicolor    versicolor
setosa    setosa
versicolor    versicolor
versicolor    versicolor
setosa    setosa
setosa    setosa
versicolor    versicolor
versicolor    versicolor
versicolor    versicolor
setosa    setosa
virginica    virginica
versicolor    versicolor
setosa    setosa
setosa    setosa
versicolor    versicolor
virginica    virginica
versicolor    versicolor
virginica    virginica
versicolor    versicolor
virginica    virginica
virginica    virginica
setosa    setosa
versicolor    versicolor
setosa    setosa


Getting accuracy and confusion matrix for the model

In [9]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(confusion_matrix(y_test,y_pred))
accuracy=accuracy_score(y_test,y_pred)*100
print(accuracy)

[[13  0  0]
 [ 0 16  0]
 [ 0  0  9]]
100.0


Testing with custom data

In [10]:
import numpy as np
x_new=np.array([[1,1,1,1]])
knn.predict(x_new)

array(['setosa'], dtype=object)